language: java
jdk: openjdk11

script:
  - version=`git tag | tail -1`
  - mvn versions:set -DnewVersion=$version
  - mvn clean package

before_deploy:
  - echo "ls"
  - ls
  - echo "ls target"
  - ls target
  - mkdir target/jars
  - cp target/*.jar target/jars

deploy:
  provider: releases
  api_key: "$GITHUB_API_KEY"
  file: "./target/search-list-sniffer-$version.jar"
  skip_cleanup: true
  on:
    tags: true